<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // 1) Add tenant_id (nullable for backfill, scoped via HasTenant trait).
        Schema::table('material_allocations', function (Blueprint $table) {
            $table->foreignId('tenant_id')->nullable()->after('allocated_by')
                ->constrained()->cascadeOnDelete();
            $table->index('tenant_id');
        });

        // 2) Backfill tenant_id from the parent work_order. Subquery form
        // is portable across Postgres and SQLite (tests).
        DB::table('material_allocations')
            ->whereNull('tenant_id')
            ->update([
                'tenant_id' => DB::raw('(SELECT tenant_id FROM work_orders WHERE work_orders.id = material_allocations.work_order_id)'),
            ]);

        // 3) Replace plain index with UNIQUE on (batch_id, material_id) to
        // prevent double allocation of the same material to the same batch.
        Schema::table('material_allocations', function (Blueprint $table) {
            // Drop the non-unique index first; name was auto-generated by Laravel.
            $table->dropIndex('material_allocations_batch_id_material_id_index');
        });

        Schema::table('material_allocations', function (Blueprint $table) {
            $table->unique(['batch_id', 'material_id'], 'material_allocations_batch_material_unique');
        });
    }

    public function down(): void
    {
        Schema::table('material_allocations', function (Blueprint $table) {
            $table->dropUnique('material_allocations_batch_material_unique');
        });

        Schema::table('material_allocations', function (Blueprint $table) {
            $table->index(['batch_id', 'material_id']);
            $table->dropForeign(['tenant_id']);
            $table->dropColumn('tenant_id');
        });
    }
};
